site:
  name: Geekgonecrazy RFDs
  url: http://localhost:8877
  logo.svg: |
    <svg width="80px" height="80px" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--emojione" preserveAspectRatio="xMidYMid meet">
      <path d="M57.6 13.7c-.7-1-1.6-1.7-2.7-2.2c-3.4-1.7-11.6-1.3-12.3-5.7c-.9-5.7-5.9.1-6.8.1c-1.1 0-1.6-3.9-3.7-3.9c-2.2 0-2.7 3.9-3.7 3.9c-.9 0-5.9-5.8-6.8-.1c-.7 4.3-9 4-12.3 5.7c-1 .5-2 1.2-2.7 2.2c-.5.8.6 1.6 1.2.9c1.6-2 4.8-2.4 7.1-2.8c1.9-.4 4-.6 5.9-1.4c2.6-1 2.5-4.9 3.3-4.9c.6 0 2.7 3 4.5 3c1.6 0 2.6-3.7 3.5-3.7c.9 0 1.9 3.7 3.5 3.7c1.9 0 4-3 4.6-3c.8 0 .7 3.9 3.3 4.9c1.8.8 3.9 1 5.9 1.4c2.3.5 5.6.8 7.1 2.8c.5.7 1.6-.2 1.1-.9" fill="#00b9f1"></path>
      <path d="M53 57c0 2.8-2.2 5-5 5H16c-2.8 0-5-2.2-5-5V36h42v21z" fill="#89967a"></path>
      <path d="M32 12c-15.5 0-21 8.5-21 24v21h42V36c0-15.5-5.5-24-21-24" fill="#b6c4a7"></path>
      <g fill="#89967a">
        <path d="M11 55c-1.1 0-2-1.2-2-2.6v-6.8c0-1.4.9-2.6 2-2.6v12"></path>
        <path d="M53 43c1.1 0 2 1.2 2 2.6v6.8c0 1.4-.9 2.6-2 2.6V43"></path>
      </g>
      <g fill="#3e4347">
        <path d="M7 20H5v30h4v-2H7z"></path>
        <path d="M57 20v28h-2v2h4V20z"></path>
      </g>
      <circle cx="58" cy="20" r="4" fill="#00b9f1"></circle>
      <circle cx="6" cy="20" r="4" fill="#ff5263"></circle>
      <path d="M21.5 39.5c-4.4 0-8-3.6-8-8s3.6-8 8-8s8 3.6 8 8s-3.6 8-8 8" fill="#efffd9"></path>
      <circle cx="21.5" cy="31.5" r="6" fill="#545b61"></circle>
      <circle cx="21.5" cy="31.5" r="2.3" fill="#ff5263"></circle>
      <path d="M42.5 39.5c-4.4 0-8-3.6-8-8s3.6-8 8-8s8 3.6 8 8s-3.6 8-8 8" fill="#efffd9"></path>
      <path d="M42.5 37.5c-3.3 0-6-2.7-6-6s2.7-6 6-6s6 2.7 6 6s-2.7 6-6 6" fill="#545b61"></path>
      <circle cx="42.5" cy="31.5" r="2.3" fill="#ff5263"></circle>
      <path d="M19.8 54.1c-7.4 0-7.4-13 0-13h24.5c7.4 0 7.4 13 0 13H19.8" fill="#efffd9"></path>
      <path d="M20.5 52.6c-6 0-6-10 0-10h23c6 0 6 10 0 10h-23" fill="#89967a"></path>
      <g opacity=".7" fill="#3e4347">
        <path d="M21.2 50.7c0 1.2-2 1.2-2 0v-6.1c0-1.2 2-1.2 2 0v6.1"></path>
        <path d="M25.9 50.7c0 1.2-2 1.2-2 0v-6.1c0-1.2 2-1.2 2 0v6.1"></path>
        <path d="M30.6 50.7c0 1.2-2 1.2-2 0v-6.1c0-1.2 2-1.2 2 0v6.1"></path>
        <path d="M35.4 50.7c0 1.2-2 1.2-2 0v-6.1c0-1.2 2-1.2 2 0v6.1"></path>
        <path d="M40.1 50.7c0 1.2-2 1.2-2 0v-6.1c0-1.2 2-1.2 2 0v6.1"></path>
        <path d="M44.8 50.7c0 1.2-2 1.2-2 0v-6.1c0-1.2 2-1.2 2 0v6.1"></path>
      </g>
      <circle cx="32" cy="37" r="2" fill="#f5f5f5"></circle>
      <path fill="#545b61" d="M30.316 35.862l.566-.565l2.828 2.828l-.565.566z"></path>
    </svg>
repo:
  username: git
  url: https://github.com/geekgonecrazy/rfd-example
  folder: rfds
  mainBranch: main
  privateDeployKey: |
    # ssh-keygen -t rsa
    # upload the other to repo deployment with write access

dataPath: ./
oidc:
  clientId: #clientId
  clientSecret: #clientSecret
  issuerUrl: https://login.yourcompanyokta.com
  authUrl: https://login.yourcompanyokta.com/oauth2/v1/authorize
  tokenUrl: https://login.yourcompanyokta.com/oauth2/v1/token
apiSecret: super-secret-api-key
jwt:
  publicKey: |
    #rsa publicKey

  privateKey: |
    #rsa privateKey
