#!/bin/bash
set -e

cd "$(dirname "$0")/.."

echo "=== RFD Tool Development Setup ==="

# Check if config.yaml already exists
if [ -f config.yaml ]; then
    echo "config.yaml already exists. Remove it first if you want to regenerate."
    exit 1
fi

# Create data directory
mkdir -p data

# Generate JWT keys if they don't exist
if [ ! -f jwt_private.pem ]; then
    echo "Generating JWT keys..."
    openssl genrsa -out jwt_private.pem 2048 2>/dev/null
    openssl rsa -in jwt_private.pem -pubout -out jwt_public.pem 2>/dev/null
    echo "  Created jwt_private.pem and jwt_public.pem"
else
    echo "  JWT keys already exist"
fi

# Generate deploy key if it doesn't exist
if [ ! -f deploy_key ]; then
    echo "Generating deploy key..."
    ssh-keygen -t rsa -b 4096 -f deploy_key -N "" -C "rfd-tool-dev" >/dev/null 2>&1
    echo "  Created deploy_key and deploy_key.pub"
    echo ""
    echo "  Add this public key to your GitHub repo as a deploy key:"
    echo "  ============================================================"
    cat deploy_key.pub
    echo "  ============================================================"
else
    echo "  Deploy key already exists"
fi

# Create config.yaml from template
echo "Creating config.yaml..."
cat > config.yaml << 'HEADER'
# Development configuration - auto-generated by setup-dev.sh

site:
  name: RFD Tool (Dev)
  url: http://localhost:8877
  logo.svg: |
    <svg width="80px" height="80px" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">
      <circle cx="32" cy="32" r="28" fill="#4a90d9"/>
      <text x="32" y="40" font-size="24" text-anchor="middle" fill="white">RFD</text>
    </svg>

repo:
  username: git
  url: https://github.com/geekgonecrazy/rfd-example
  folder: rfds
  mainBranch: main
  commitAuthorName: RFD-Tool
  commitAuthorEmail: rfdtool@localhost
  privateDeployKey: |
HEADER

# Add deploy key with proper indentation
sed 's/^/    /' deploy_key >> config.yaml

cat >> config.yaml << 'MIDDLE'

dataPath: ./data/

oidc:
  clientId: rfd-tool-dev
  clientSecret: rfd-tool-dev-secret
  issuerUrl: http://localhost:5556/dex
  authUrl: http://localhost:5556/dex/auth
  tokenUrl: http://localhost:5556/dex/token

apiSecret: dev-api-secret-change-in-production

jwt:
  publicKey: |
MIDDLE

# Add JWT public key with proper indentation
sed 's/^/    /' jwt_public.pem >> config.yaml

cat >> config.yaml << 'PRIVATE'

  privateKey: |
PRIVATE

# Add JWT private key with proper indentation
sed 's/^/    /' jwt_private.pem >> config.yaml

echo "  Created config.yaml"

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Add the deploy key to your GitHub repo (Settings -> Deploy keys)"
echo "  2. Start Dex:  docker compose up -d"
echo "  3. Build:      go build -o rfd-server ./cmd/rfd-server"
echo "  4. Run:        ./rfd-server"
echo "  5. Open:       http://localhost:8877"
echo ""
echo "Test users (password: 'password'):"
echo "  - alice@acme.com"
echo "  - bob@acme.com"
echo "  - carol@acme.com"
echo "  - dave@acme.com"
